spring.application.name=gerenciador-pedidos
spring.datasource.url=jdbc:postgresql://localhost/gerenciador-pedidos
spring.datasource.username=postgres
spring.datasource.password=Babaca16#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
